### ISSUE TITLE
Needs Google Analytics / App Insights to track usage

### ISSUE THREAD

**Issue by matthewfrye** [matthewfrye/CookieOrders#21]

**Comment by daveabrock** [comment]
@matthewfrye might want to work on getting this together, since we are using his Azure account(s). This [article](https://docs.microsoft.com/en-us/azure/azure-monitor/app/usage-segmentation) should help.

**Comment by matthewfrye** [comment]
Chose to use Google Analytics since it was free versus the small charge of App Insights.  Added in latest pull request [https://github.com/matthewfrye/CookieOrders/pull/34](url)
